site_name: Technical Tutorials Hub
site_description: Hands-on guides for Kubernetes, Docker, Automation and more
site_author: Garrett Stack
site_url: https://garstack-sharetribe.github.io/gstack-tech-guides/

repo_url: https://github.com/garstack-sharetribe/gstack-tech-guides
repo_name: garstack-tech-guides

copyright: © 2026 Garrett Stack

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/garstack-sharetribe
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/yourprofile
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourhandle

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid-init.js
  - javascripts/extra.js

plugins:
  - search

  - mermaid2

  - glightbox:
      touchNavigation: true
      zoomable: true
      draggable: true

theme:
  name: material
  icon:
    repo: fontawesome/brands/github

  palette:
    primary: indigo
    accent: blue

  features:
    # Navigation
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - navigation.path
    - navigation.indexes

    # Content
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

    # Table of contents
    - toc.follow

    # Search
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true


      
nav:
  - Home: index.md
  - "🐳 Docker  (🚧 Planned)":
    - Overview: docker/index.md
    - Tutorials:
      - Index: docker/tutorials/index.md
      - Beginner:
         - Index: docker/tutorials/beginner/index.md
#        - Overview: docker/tutorials/beginner/01-high-level-overview.md
#        - Recap & Tips: docker/tutorials/beginner/06-recap-and-tips.md
      - Intermediate:
         - Index: docker/tutorials/intermediate/index.md
#        - Overview: docker/tutorials/intermediate/01-overview.md
#        - Troubleshooting: docker/tutorials/intermediate/06-troubleshooting.md
      - Advanced:
         - Index: docker/tutorials/intermediate/index.md
#        - Overview: docker/tutorials/advanced/01-overview.md
#        - StatefulSets: docker/tutorials/advanced/06-statefulsets.md
    - How-To Guides:
      - Index: docker/how-to/index.md
#      - Troubleshoot Pods: docker/how-to/troubleshooting.md
#    - Explanation:
#      - Index: docker/explanation/index.md
#      - Namespaces: docker/explanation/namespaces.md
#    - Reference:
#      - Index: docker/reference/index.md
#      - StatefulSets: docker/reference/statefulsets.md

  - "☸ Kubernetes (🚧 In Progress)":
    - Overview: kubernetes/index.md
    - Tutorials:
      - Index: kubernetes/tutorials/index.md
      - Beginner:
        - Index: kubernetes/tutorials/beginner/index.md
        - High Level Overview: kubernetes/tutorials/beginner/high-level-overview.md
        - Install Minikube: kubernetes/tutorials/beginner/install-minikube.md
        - Your First Pod: kubernetes/tutorials/beginner/your-first-pod-and-deployment.md
        - Deployments: kubernetes/tutorials/beginner/deployments.md
        - Services: kubernetes/tutorials/beginner/services.md
        - Recap & Tips: kubernetes/tutorials/beginner/recap-and-tips.md
      - Intermediate:
        - Index: kubernetes/tutorials/intermediate/index.md
        - Deploy Multi Container: kubernetes/tutorials/intermediate/deploy-multi-container-app.md
        - ConfigMaps: kubernetes/tutorials/intermediate/configmaps.md       
        - Secrets: kubernetes/tutorials/intermediate/secrets.md
        - Persistent Volumes: kubernetes/tutorials/intermediate/persistent-volumes-and-storage.md
        - Perform a Rolling Update and Rollback: kubernetes/tutorials/intermediate/rolling-update-and-rollback.md
        - Expose App With Ingress: kubernetes/tutorials/intermediate/expose-app-with-ingress.md
      - Advanced:
        - Index: kubernetes/tutorials/advanced/index.md
        - Ingress: kubernetes/tutorials/advanced/ingress.md
        - Helm Basics: kubernetes/tutorials/advanced/helm-basics.md
        - Resource Limits & HPA: kubernetes/tutorials/advanced/resource-limits-and-requests.md
        - RBAC & Network Policies: kubernetes/tutorials/advanced/rbac-and-network-policies.md
        - StatefulSets: kubernetes/tutorials/advanced/statefulsets-headless-services.md
        - Wrap Up: kubernetes/tutorials/advanced/final-wrap-up.md
      - End-to-End Tutorials:
        - Deploy Your First Application: kubernetes/tutorials/end-to-end/deploy-your-first-application.md
        - Scale an Application: kubernetes/tutorials/end-to-end/scale-an-application.md
        - Debug a Failing Application: kubernetes/tutorials/end-to-end/debug-a-failing-application.md
    - How-To Guides:
      - Index: kubernetes/how-to/index.md
      - Deployments:
        - Overview: kubernetes/how-to/deployments/index.md
        - Scale Deployment: kubernetes/how-to/deployments/scale-deployment.md
        - Rollback Deployment: kubernetes/how-to/deployments/rollback-deployment.md
        - Restart Deployment: kubernetes/how-to/deployments/restart-deployment.md
        - Update Container Image: kubernetes/how-to/deployments/update-container-image.md
      - Networking:
        - Overview: kubernetes/how-to/networking/index.md
        - Expose Service: kubernetes/how-to/networking/expose-service.md
        - Expose Service Ingress: kubernetes/how-to/networking/expose-service-ingress.md
        - Port Forward Pod: kubernetes/how-to/networking/port-forward-pod.md
      - Configuration:
        - Overview: kubernetes/how-to/configuration/index.md
        - Use Configmaps: kubernetes/how-to/configuration/use-configmaps.md
        - Use Secrets: kubernetes/how-to/configuration/use-secrets.md
        - Add Env Vars: kubernetes/how-to/configuration/add-env-vars.md
      - Storage: 
        - Overview: kubernetes/how-to/storage/index.md
        - Mount Persistent Volume: kubernetes/how-to/storage/mount-persistent-volume.md
    - Explanation:
      - Index: kubernetes/explanation/index.md
      - Container Fundamentals:
        - What is Docker: kubernetes/container-fundamentals/what-is-docker.md
        - Container vs VM: kubernetes/container-fundamentals/container-vs-docker.md
        - Building a Docker Image: kubernetes/container-fundamentals/building-a-docker-image.md
      - Architecture: 
        - Kubernetes Architecture Overview: kubernetes/architecture/kubernetes-architecture-overview.md
        - Control Plane Components: kubernetes/architecture/control-plane-components.md
        - Worker Node Components: kubernetes/architecture/worker-node-components.md
        - Request Flow Through Kubernetes: kubernetes/architecture/request-flow-through-kubernetes.md
      - Workloads:
        - Index: kubernetes/explanation/workloads/index.md
        - Pods: kubernetes/explanation/workloads/pods.md
        - Deployments: kubernetes/explanation/workloads/deployments.md
        - Replica Sets: kubernetes/explanation/workloads/replica-sets.md
        - Stateful Sets: kubernetes/explanation/workloads/statefulsets.md
      - Networking:
        - Index: kubernetes/explanation/networking/index.md
        - Pod Networking: kubernetes/explanation/networking/pod-networking.md
        - Services: kubernetes/explanation/networking/services.md
        - Kube Proxy: kubernetes/explanation/networking/kube-proxy.md
        - Ingress: kubernetes/explanation/networking/ingress.md
        - DNS: kubernetes/explanation/networking/dns.md
        - Network Policies: kubernetes/explanation/networking/network-policies.md
      - Configuration:
        - Index: kubernetes/explanation/configuration/index.md
        - Configmaps: kubernetes/explanation/configuration/configmaps.md
        - Secrets: kubernetes/explanation/configuration/secrets.md
      - Storage:
        - Index: kubernetes/explanation/storage/index.md
        - Persistent Volumes: kubernetes/explanation/storage/persistent-volumes.md
        - Persistent Volume Claims: kubernetes/explanation/storage/persistent-volume-claims.md
      - Scaling:
        - Index: kubernetes/explanation/scaling/index.md
        - Horizontal Pod Autoscaler: kubernetes/explanation/scaling/horizontal-pod-autoscaler.md
        - Rolling Updates: kubernetes/explanation/scaling/rolling-updates.md
    - Reference:
      - Index: kubernetes/reference/index.md
      - kubectl Commands:
        - kubectl Overview: kubernetes/reference/kubectl/kubectl-overview.md
        - kubectl get: kubernetes/reference/kubectl/kubectl-get.md
        - kubectl describe: kubernetes/reference/kubectl/kubectl-describe.md
        - kubectl logs: kubernetes/reference/kubectl/kubectl-logs.md
        - kubectl exec: kubernetes/reference/kubectl/kubectl-exec.md
        - kubectl apply: kubernetes/reference/kubectl/kubectl-apply.md
      - Kubernetes Objects:
        - Pods: kubernetes/reference/objects/pods.md
        - Deployments: kubernetes/reference/objects/deployments.md
        - Services: kubernetes/reference/objects/services.md
        - ConfigMaps: kubernetes/reference/objects/configmaps.md
        - Secrets: kubernetes/reference/objects/secrets.md
        - StatefulSets: kubernetes/reference/objects/statefulsets.md
      - Resource Management:
        - Resource Requests & Limits: kubernetes/reference/resources/resource-limits.md
        - Horizontal Pod Autoscaler: kubernetes/reference/resources/hpa.md

    - Scaling & Resources:
      - Resource Limits: kubernetes/reference/resource-limits.md
      - Horizontal Pod Autoscaler: kubernetes/reference/hpa.md

    - Security:
      - RBAC: kubernetes/reference/rbac.md
      - Network Policies: kubernetes/reference/network-policies.md

#    - Ecosystem Tools:
#      - Helm Basics: kubernetes/reference/helm-basics.md
#      - Ingress: kubernetes/reference/ingress.md
#      - Helm Basics: kubernetes/reference/helm-basics.md
#      - Resource Limits & HPA: kubernetes/reference/hpa.md
#      - RBAC & Network Policies: kubernetes/reference/rbac-network-policies.md
#      - StatefulSets: kubernetes/reference/statefulsets.md

    - Troubleshooting:
      - Overview: kubernetes/troubleshooting/index.md
      - Pods:
        - CrashLoopBackOff: kubernetes/troubleshooting/CrashLoopBackOff.md
        - ImagePullBackOff: kubernetes/troubleshooting/ImagePullBackOff.md
        - Pod Stuck Pending: kubernetes/troubleshooting/pod-stuck-pending.md
      - Networking:
        - Service Not Reachable: kubernetes/troubleshooting/service-not-reachable.md
      - Debugging:
        - Kubectl-Debugging: kubernetes/troubleshooting/kubectl-debugging.md


  - "⚡Automation (🚧 Planned)":
    - Overview: automation/index.md
    - Tutorials:
      - Index: automation/tutorials/index.md
      - Beginner:
         - Overview: automation/tutorials/beginner/index.md
#        - Overview: automation/tutorials/beginner/01-high-level-overview.md
#        - Recap & Tips: automation/tutorials/beginner/06-recap-and-tips.md
      - Intermediate:
         - Overview: automation/tutorials/intermediate/index.md
#        - Overview: automation/tutorials/intermediate/01-overview.md
#        - Troubleshooting: automation/tutorials/intermediate/06-troubleshooting.md
      - Advanced:
         - Overview: automation/tutorials/advanced/index.md
#        - Overview: automation/tutorials/advanced/01-overview.md
#        - StatefulSets: automation/tutorials/advanced/06-statefulsets.md
    - How-To Guides:
      - Index: automation/how-to/index.md
#      - Troubleshoot Pods: automation/how-to/troubleshooting.md
    - Explanation:
      - Index: automation/explanation/index.md
#      - Namespaces: automation/explanation/namespaces.md
    - Reference:
      - Index: automation/reference/index.md
#      - StatefulSets: automation/reference/statefulsets.md

extra:
  mermaid:
    theme: default